### ISSUE TITLE
Code for SelfCheckGPT?

### ISSUE THREAD

**Issue by xlchen0205** [yakir-yehuda/InterrogateLLM#3]
Hi,

My apologies for disturbing you again.

Could you please upload the code related to SelfCheckGPT with Prompt? Thank you.

**Comment by xlchen0205** [comment]
Could you please find some time to reply? Your response will be invaluable to me.

Thank you in advance for your time and consideration.

**Comment by yakir-yehuda** [comment]
Hi,

Sorry for the delayed response.

You can find the code for SelfCheckGPT in the following repository: https://github.com/potsawee/selfcheckgpt.
For using it with the SelfCheckGPT Usage: LLM Prompt option, it's just a few lines of code—everything you need is in the repo.

**Comment by xlchen0205** [comment]
> Hi,
> 
> Sorry for the delayed response.
> 
> You can find the code for SelfCheckGPT in the following repository: https://github.com/potsawee/selfcheckgpt. For using it with the SelfCheckGPT Usage: LLM Prompt option, it's just a few lines of code—everything you need is in the repo.

Thanks a lot :)
